import React,{useState,useEffect,useRef} from 'react';
const normalize=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const compact=value=>normalize(value).replace(/[^a-z0-9]/g,'');
export function AudioSearch({entry,disabled,onSelect,onTrackSelect,onUploadBusy}){
 const [open,setOpen]=useState(false);const [mode,setMode]=useState('library');const [query,setQuery]=useState('');const [artist,setArtist]=useState('');const [region,setRegion]=useState('FR');const [audios,setAudios]=useState([]);const [tracks,setTracks]=useState([]);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [uploading,setUploading]=useState(null);const [visible,setVisible]=useState(40);const [searched,setSearched]=useState(false);const request=useRef(0);const locked=disabled||uploading!==null;
 useEffect(()=>{if(!open)return;let alive=true;const load=async()=>{try{const response=await fetch('/api/audio-library');const result=await response.json();if(!response.ok)throw Error(result.error);if(alive)setAudios(result.audios);}catch{if(alive)setError('Bibliothèque inaccessible. Redémarrez l’application après sa mise à jour.');}};load();window.addEventListener('audio-library-updated',load);return()=>{alive=false;window.removeEventListener('audio-library-updated',load);};},[open]);
 async function search(event){event.preventDefault();const current=++request.current;setLoading(true);setError('');setTracks([]);setSearched(false);setVisible(40);try{const params=new URLSearchParams({q:[query,artist].filter(Boolean).join(' ').trim(),artist,region});const response=await fetch('/api/music-search?'+params);let result;try{result=await response.json();}catch{throw Error('Recherche indisponible. Redémarrez l’application après sa mise à jour.');}if(!response.ok)throw Error(result.error);if(current===request.current){setTracks(result.tracks);setSearched(true);}}catch(e){if(current===request.current)setError(e.message);}finally{if(current===request.current)setLoading(false);}}
 function select(audio,track){onSelect({...audio,title:track?.title,artist:track?.artist});setOpen(false);}
 async function importForTrack(file,track){if(!file)return;setError('');setUploading(track.id);onUploadBusy?.(true);try{if(file.size>100*1024*1024)throw Error('100 Mo maximum par fichier audio.');const body=new FormData();body.append('audio',file);const response=await fetch('/api/audio',{method:'POST',body});let audio;try{audio=await response.json();}catch{throw Error('Serveur audio indisponible. Redémarrez l’application.');}if(!response.ok)throw Error(audio.error);if(!audio.url||!Number.isFinite(audio.duration))throw Error('Le serveur audio doit être mis à jour.');onTrackSelect?.(track);select(audio,track);window.dispatchEvent(new Event('audio-library-updated'));}catch(e){setError(e.message);}finally{setUploading(null);onUploadBusy?.(false);}}
 return <div className="audio-search"><button type="button" disabled={locked} aria-expanded={open} onClick={()=>setOpen(!open)}>RECHERCHER UN AUDIO</button>{open&&<div className="audio-search-panel">
 <div className="audio-search-tabs"><button type="button" disabled={locked} aria-pressed={mode==='library'} onClick={()=>{request.current++;setLoading(false);setMode('library');setQuery('');setError('');}}>MES AUDIOS</button><button type="button" disabled={locked} aria-pressed={mode==='catalogue'} onClick={()=>{setMode('catalogue');setQuery(entry.title||'');setArtist(entry.artist||'');setTracks([]);setSearched(false);setError('');}}>CATALOGUE</button></div>
 <form onSubmit={mode==='catalogue'?search:event=>event.preventDefault()}><input aria-label="Recherche audio" placeholder={mode==='library'?'Nom du fichier…':'Titre du morceau…'} value={query} disabled={locked} onChange={e=>setQuery(e.target.value)}/>{mode==='catalogue'&&<button disabled={locked||loading||[query,artist].join('').trim().length<2}>{loading?'RECHERCHE…':'CHERCHER'}</button>}</form>
 {mode==='catalogue'&&<div className="catalogue-filters"><label>ARTISTE<input aria-label="Artiste du catalogue" placeholder="PLK, Ninho, Laylow…" value={artist} disabled={locked} onChange={e=>setArtist(e.target.value)}/></label><label>CATALOGUE<select aria-label="Région du catalogue" value={region} disabled={locked} onChange={e=>setRegion(e.target.value)}><option value="FR">France · priorité rap français</option><option value="all">Recherche élargie · France, US, UK</option><option value="US">États-Unis</option><option value="GB">Royaume-Uni</option></select></label></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 {mode==='library'?<div className="audio-search-results">{audios.filter(audio=>normalize(audio.name).includes(normalize(query))).map(audio=><div key={audio.url} className="audio-search-result"><strong>{audio.name}</strong><audio controls preload="none" src={audio.url}/><button disabled={locked} onClick={()=>select(audio)}>UTILISER CET AUDIO</button></div>)}{!audios.length&&<p className="hint">Importe tes fichiers dans la bibliothèque.</p>}{audios.length>0&&!audios.some(audio=>normalize(audio.name).includes(normalize(query)))&&<p className="hint">Aucun audio trouvé.</p>}</div>:<>
 <p className="hint">Aperçus pour l’écoute. Pour ajouter le son au MP4, choisis un fichier de ta bibliothèque ou importe-le sous le morceau.</p>
 {searched&&<p className="hint">{tracks.length} morceau(s) trouvé(s).</p>}
 <div className="audio-search-results">{tracks.slice(0,visible).map(track=>{const matching=track.title?audios.filter(audio=>compact(audio.name).includes(compact(track.title))):[];return <div key={track.id} className="audio-search-result"><strong>{track.title}</strong><span>{track.artist} · {track.album}</span>{track.preview?<audio aria-label={`Extrait de ${track.title}`} controls preload="none" src={track.preview}/>:<small>Extrait indisponible</small>}{onTrackSelect&&<button disabled={locked} onClick={()=>onTrackSelect(track)}>REPRENDRE TITRE ET ARTISTE</button>}{matching.map(audio=><button key={audio.url} disabled={locked} onClick={()=>{onTrackSelect?.(track);select(audio,track);}}>AJOUTER L’AUDIO : {audio.name}</button>)}<label className="catalogue-upload">{uploading===track.id?'IMPORT EN COURS…':'AJOUTER MON FICHIER AUDIO'}<input type="file" aria-label={`Ajouter audio ${track.title}`} accept="audio/*,.mp3,.wav,.m4a,.flac,.ogg,.aac" disabled={locked} onChange={e=>{importForTrack(e.target.files[0],track);e.target.value='';}}/></label>{track.link&&<a href={track.link} target="_blank" rel="noreferrer">APPLE MUSIC ↗</a>}</div>;})}{searched&&tracks.length===0&&<p className="hint">Aucun morceau trouvé. Essaie avec le nom de l’artiste seul.</p>}{!searched&&!loading&&!error&&<p className="hint">Recherche un titre ou un artiste.</p>}{tracks.length>visible&&<button disabled={locked} onClick={()=>setVisible(n=>n+40)}>AFFICHER PLUS DE MORCEAUX</button>}</div></>}
 </div>}</div>;
}
