import React from 'react';
import {AbsoluteFill,Img,Audio,Sequence,useCurrentFrame,interpolate} from 'remotion';
import {smoothProgress,phaseOpacity} from '../motion.mjs';
import {orderedEntries,topTiming,audioVolume,audioLevel} from './model.mjs';
export function TopVideo({data}){
 const frame=useCurrentFrame();const t=topTiming(data);const entries=orderedEntries(data);const recap=smoothProgress(frame,t.summaryStart-15,30);const zoom=interpolate(frame,[0,t.duration],[1.05,1.13]);
 return <AbsoluteFill style={{fontFamily:'Arial, sans-serif',background:'#0e0d14',color:'#f5efff'}}>
 {data.background&&<Img src={data.background} style={{position:'absolute',width:'100%',height:'100%',objectFit:'cover',objectPosition:'center',filter:'blur(8px)',transform:`scale(${zoom})`}}/>}
 <AbsoluteFill style={{background:'linear-gradient(180deg,#080812aa,#080812cc 45%,#080812ee)'}}/>
 {frame<t.introEnd+12&&<div style={{position:'absolute',top:280,left:120,right:120,textAlign:'center',opacity:smoothProgress(frame,0,18)*(1-smoothProgress(frame,t.introEnd-12,24)),transform:`translateY(${(1-smoothProgress(frame,0,24))*12}px)`}}>{data.background&&<Img src={data.background} style={{width:620,height:760,objectFit:'cover',objectPosition:'center',borderRadius:10,boxShadow:'0 30px 80px #0008'}}/>}<div style={{fontSize:data.name?.length>100?38:data.name?.length>50?54:76,fontWeight:700,lineHeight:1.15,marginTop:60,overflowWrap:'anywhere'}}>{data.name||'Mon top'}</div></div>}
 {recap<1&&entries.map((entry,i)=>{const start=t.introEnd+i*t.itemFrames;const end=start+t.itemFrames;const opacity=phaseOpacity(frame,start,Infinity,24)*(1-smoothProgress(frame,end-12,24))*(1-recap);if(opacity<=0)return null;const entrance=smoothProgress(frame,start-12,36);const scale=(entry.rank===1?.95:.98)+(entry.rank===1?.05:.02)*entrance;return <div key={entry.id} style={{position:'absolute',top:310,left:80,right:80,textAlign:'center',opacity,transform:`translateY(${(1-entrance)*14}px)`}}><div style={{fontSize:27,letterSpacing:5,color:entry.rank===1?'#f5c84c':'#c4aedf'}}>N° {String(entry.rank).padStart(2,'0')}</div>{entry.cover?<Img src={entry.cover} style={{width:650,height:650,objectFit:'cover',borderRadius:10,marginTop:38,boxShadow:'0 30px 80px #0008',transform:`scale(${scale})`}}/>:<div style={{width:650,height:650,background:'#24202c',margin:'38px auto 0',borderRadius:10}}/>}<div style={{fontSize:entry.title.length>60?48:76,fontWeight:700,lineHeight:1.14,marginTop:60,overflowWrap:'anywhere'}}>{entry.title||'Titre du morceau'}</div><div style={{fontSize:46,color:'#cbbad9',marginTop:25,overflowWrap:'anywhere'}}>{entry.artist||'Artiste'}</div></div>})}
 {entries.map((entry,i)=>{if(!entry.audio)return null;const from=Math.round(t.introEnd+i*t.itemFrames);const length=Math.round(t.introEnd+(i+1)*t.itemFrames)-from;const available=Math.max(1,Math.floor((entry.audioDuration-entry.audioStart)*30));const duration=Math.min(length,available);return <Sequence key={`audio-${entry.id}`} from={from} durationInFrames={duration}><Audio src={entry.audio} startFrom={Math.round(entry.audioStart*30)} volume={f=>audioLevel(data,entry)*audioVolume(f,duration)}/></Sequence>;})}
 {recap>0&&<TopSummary data={data} opacity={recap}/>}
 </AbsoluteFill>;
}
function TopSummary({data,opacity}){const count=data.entries.length;const columns=count>10?2:1;const rows=Math.max(1,Math.ceil(count/columns));const coverSize=Math.max(30,Math.min(105,1230/rows-18));return <AbsoluteFill style={{top:270,bottom:100,left:80,right:80,width:'auto',height:'auto',opacity,display:'flex',flexDirection:'column',gap:28}}><div style={{fontSize:23,letterSpacing:7,color:'#baa8d3',textAlign:'center'}}>{data.name}</div><div style={{flex:1,minHeight:0,display:'grid',gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`,gridTemplateRows:`repeat(${rows},minmax(0,1fr))`,gridAutoFlow:'column',columnGap:30}}>{data.entries.map((entry,i)=><div key={entry.id} style={{display:'flex',alignItems:'center',gap:16,minHeight:0,borderBottom:'1px solid #ffffff20'}}><span style={{fontSize:count>10?22:30,color:i===0?'#f5c84c':'#a897bd',width:36,flexShrink:0,fontWeight:700}}>{String(i+1).padStart(2,'0')}</span>{entry.cover&&<Img src={entry.cover} style={{width:coverSize,height:coverSize,objectFit:'cover',borderRadius:5,flexShrink:0}}/>}<div style={{minWidth:0,overflowWrap:'anywhere'}}><div style={{fontSize:entry.title.length>60?18:count>10?25:34,lineHeight:1.15,color:i===0?'#f4deb0':'#f3eefa',fontWeight:600}}>{entry.title}</div><div style={{fontSize:count>10?19:24,color:'#baacca',marginTop:9}}>{entry.artist}</div></div></div>)}</div></AbsoluteFill>;}
