import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import ffmpeg from 'ffmpeg-static';import {readFileSync} from 'node:fs';
const baseURL=process.env.TEST_BASE_URL||'http://localhost:3000';const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{
 const page=await browser.newPage();await page.route('**/api/music-search?*',route=>{const params=new URL(route.request().url()).searchParams;assert.equal(params.get('region'),'FR');assert.equal(params.get('artist'),'PLK');return route.fulfill({json:{tracks:Array.from({length:61},(_,i)=>({id:i+1,title:i===0?'Tout recommencer':`Morceau ${i}`,artist:'PLK',album:'Album',preview:null}))}});});
 await page.goto(baseURL+'/le-top.html');await page.getByRole('button',{name:'RECHERCHER UN AUDIO',exact:true}).click();await page.getByRole('button',{name:'CATALOGUE',exact:true}).click();await page.getByLabel('Recherche audio',{exact:true}).fill('Tout re commencer');await page.getByLabel('Artiste du catalogue',{exact:true}).fill('PLK');await page.getByRole('button',{name:'CHERCHER',exact:true}).click();await expect(page.locator('.audio-search-result')).toHaveCount(40);await page.getByRole('button',{name:'AFFICHER PLUS DE MORCEAUX',exact:true}).click();await expect(page.locator('.audio-search-result')).toHaveCount(61);
 execFileSync(ffmpeg,['-y','-v','error','-f','lavfi','-i','sine=frequency=440:duration=3','/tmp/catalogue-tone.wav']);await page.getByLabel('Ajouter audio Tout recommencer',{exact:true}).setInputFiles({name:'PLK - Tout recommencer.wav',mimeType:'audio/wav',buffer:readFileSync('/tmp/catalogue-tone.wav')});await page.locator('.top-entry audio').waitFor();await expect(page.getByLabel('Titre 1',{exact:true})).toHaveValue('Tout recommencer');await expect(page.getByLabel('Artiste 1',{exact:true})).toHaveValue('PLK');const source=await page.locator('.top-entry audio').getAttribute('src');const audio=await page.request.get(baseURL+source);assert.equal(audio.status(),200);assert.match(audio.headers()['content-type'],/audio\/mpeg/);
 await page.goto(baseURL+'/decouverte.html');await page.getByRole('button',{name:'RECHERCHER UN AUDIO',exact:true}).click();await page.getByRole('button',{name:'CATALOGUE',exact:true}).click();await page.getByLabel('Recherche audio',{exact:true}).fill('Tout recommencer');await page.getByLabel('Artiste du catalogue',{exact:true}).fill('PLK');await page.getByRole('button',{name:'CHERCHER',exact:true}).click();await page.getByRole('button',{name:'AJOUTER L’AUDIO : PLK - Tout recommencer.wav',exact:true}).first().click();await page.locator('.editor audio').waitFor();await expect(page.getByLabel('TITRE DU MORCEAU',{exact:true})).toHaveValue('Tout recommencer');await expect(page.getByLabel('ARTISTE',{exact:true})).toHaveValue('PLK');assert.equal(await page.locator('.editor audio').getAttribute('src'),source);
 console.log('Mocked French catalogue: 61 results, show more, real file import from a result in TOP, library matching in Discovery and correct metadata: PASS');
}finally{await browser.close();}
