import {chromium,expect} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {execFileSync} from 'node:child_process';import ffmpeg from 'ffmpeg-static';
const baseURL=process.env.TEST_BASE_URL||'http://localhost:3000';const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(baseURL+'/');await page.getByRole('link',{name:'La Découverte ↗',exact:true}).click();await expect(page).toHaveTitle('La Découverte — Video Studio');await page.getByRole('button',{name:'GÉNÉRER LA VIDÉO'}).click();await expect(page.getByRole('alert')).toContainText('pochette');
 await page.getByLabel('GRAND TITRE AU-DESSUS DE LA POCHETTE',{exact:true}).fill('LA DÉCOUVERTE DU JOUR');await page.getByLabel('TITRE DU MORCEAU',{exact:true}).fill('ÉTÉ');await page.getByLabel('ARTISTE',{exact:true}).fill('Mon artiste');
 const image=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=700;const x=c.getContext('2d');x.fillStyle='#543e64';x.fillRect(0,0,700,700);x.fillStyle='#d3b99a';x.font='bold 90px Arial';x.fillText('ÉTÉ',260,385);return Array.from(Uint8Array.from(atob(c.toDataURL('image/png').split(',')[1]),c=>c.charCodeAt(0)));}));await page.getByLabel('Pochette découverte',{exact:true}).setInputFiles({name:'cover.png',mimeType:'image/png',buffer:image});await page.getByAltText('Pochette importée').waitFor();await expect(page.locator('.player-shell').getByText('LA DÉCOUVERTE DU JOUR')).toBeVisible();
 execFileSync(ffmpeg,['-v','error','-y','-f','lavfi','-i','sine=frequency=440:duration=4','/tmp/discovery-tone.wav']);await page.getByLabel('Audio découverte',{exact:true}).setInputFiles('/tmp/discovery-tone.wav');await page.locator('.editor audio').waitFor();await page.getByLabel('Volume découverte',{exact:true}).press('Home');await page.getByLabel('Volume découverte',{exact:true}).press('End');await page.getByLabel('Durée découverte',{exact:true}).press('Home');await page.getByLabel('Animation musicale',{exact:true}).selectOption('off');await page.getByLabel('Animation musicale',{exact:true}).selectOption('on');await page.screenshot({path:'/tmp/discovery-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'GÉNÉRER LA VIDÉO'}).click();await page.getByRole('link',{name:'TÉLÉCHARGER MP4'}).waitFor({timeout:240000});const url=await page.getByRole('link',{name:'TÉLÉCHARGER MP4'}).getAttribute('href');const response=await page.request.get(baseURL+url);assert.equal(response.status(),200);assert.match(response.headers()['content-disposition'],/la-decouverte.mp4/);await fs.writeFile('/tmp/discovery-test.mp4',await response.body());const info=JSON.parse(execFileSync('ffprobe',['-v','error','-show_streams','-of','json','/tmp/discovery-test.mp4'],{encoding:'utf8'}));const video=info.streams.find(s=>s.codec_type==='video');assert.equal(video.width,1080);assert.equal(video.height,1920);assert.equal(video.nb_frames,'90');assert.equal(video.r_frame_rate,'30/1');assert.ok(info.streams.some(s=>s.codec_type==='audio'));
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/discovery-mobile.png',fullPage:true});await page.getByRole('link',{name:'LE TOP',exact:true}).click();await expect(page).toHaveTitle('LE TOP — Video Studio');assert.deepEqual(errors,[]);console.log('Discovery navigation, live preview, cover/audio, duration, animation toggle, mobile and real 1080x1920 MP4 with audio: PASS');
}finally{await browser.close();}
