import test from 'node:test';import assert from 'node:assert/strict';
import {topTiming,orderedEntries,validateTop,parseTop,audioVolume} from '../src/top/model.mjs';
const image='data:image/jpeg;base64,eA==';const data={name:'Mon top',background:image,entries:Array.from({length:3},(_,i)=>({id:String(i),title:`Titre ${i}`,artist:'Artiste',cover:image})),revealOrder:'countdown',endScreenSeconds:5};
test('Countdown ends at number one; recap keeps original ranking without mutation',()=>{assert.deepEqual(orderedEntries(data).map(e=>e.rank),[3,2,1]);assert.deepEqual(orderedEntries({...data,revealOrder:'ascending'}).map(e=>e.rank),[1,2,3]);assert.equal(data.entries[0].id,'0');});
test('Top duration supports automatic, manual and independently adjustable ending',()=>{const t=topTiming(data);assert.equal(t.duration,420);assert.equal(t.summaryStart,270);assert.equal(topTiming({...data,durationSeconds:20}).duration,600);assert.equal(topTiming({...data,durationSeconds:1}).duration,330);assert.equal(topTiming({...data,endScreenSeconds:10}).duration,570);assert.equal(topTiming({...data,endScreenSeconds:10}).endFrames,300);});
test('Top import preserves names and rejects incomplete lines atomically',()=>{assert.deepEqual(parseTop('1. MENACE — Laylow\nRYUK\tÉté\nA - B'),[{title:'MENACE',artist:'Laylow'},{title:'RYUK',artist:'Été'},{title:'A',artist:'B'}]);assert.throws(()=>parseTop('MENACE — Laylow\nINVALIDE'),/Ligne 2/);assert.throws(()=>parseTop(''));});
test('Top export requires background, title, artist and each cover; remote images rejected',()=>{assert.doesNotThrow(()=>validateTop(data));assert.throws(()=>validateTop({...data,background:'https://example.com/photo.jpg'}));assert.throws(()=>validateTop({...data,entries:[{...data.entries[0],cover:''}]}),/N°1/);assert.throws(()=>validateTop({...data,entries:[{...data.entries[0],artist:''}]}));assert.throws(()=>validateTop({...data,entries:[]}));});

test('Top begins immediately and restricts audio to uploaded files and valid offsets',()=>{assert.equal(topTiming(data).introEnd,0);const audioEntry={...data.entries[0],audio:'/api/audio/12345678-1234-1234-1234-123456789abc',audioDuration:10,audioStart:2};assert.doesNotThrow(()=>validateTop({...data,entries:[audioEntry]}));for(const patch of [{audio:'https://example.com/song.mp3'},{audioStart:10},{audioStart:-1}])assert.throws(()=>validateTop({...data,entries:[{...audioEntry,...patch}]}));});

test("Audio fades softly at both ends, including very short excerpts",()=>{assert.equal(audioVolume(0,90),0);assert.equal(audioVolume(6,90),.5);assert.equal(audioVolume(30,90),1);assert.equal(audioVolume(83,90),.5);assert.equal(audioVolume(89,90),0);assert.equal(audioVolume(0,1),0);assert.ok(audioVolume(2,6)<=1);});
