import React from 'react';
import {AbsoluteFill,Img,useCurrentFrame,interpolate} from 'remotion';
import {categories,category,timing} from './model.mjs';
const fade=(f,start,length=16)=>interpolate(f,[start,start+length],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
const format=n=>String(n).replace('.',',');
export function AlbumVideo({data}){const f=useCurrentFrame();const t=timing(data.tracks,data.durationSeconds);const isTracks=f>=90&&f<t.tracksEnd;const isResult=f>=t.tracksEnd&&f<t.resultEnd;const isTop=f>=t.resultEnd;const page=Math.max(0,t.pageStarts.findLastIndex(start=>f>=start));const start=t.pageStarts[page]||90;const visible=t.pages[page]||[];const scale=interpolate(f,[0,t.duration],[1.07,1.14]);return <AbsoluteFill style={{background:'#101015',color:'#f6f4fa',fontFamily:'Arial, sans-serif',overflow:'hidden'}}>
{data.cover&&<Img src={data.cover} style={{position:'absolute',width:'100%',height:'100%',objectFit:'cover',objectPosition:'center',filter:'blur(16px)',transform:`scale(${scale})`}}/>}
<AbsoluteFill style={{background:'linear-gradient(180deg,rgba(8,8,14,.65),rgba(8,8,14,.88) 70%,rgba(8,8,14,.96))'}}/>
<div style={{position:'absolute',top:105,left:80,fontSize:24,letterSpacing:8,color:'#b4afb9'}}>ALBUM / REVIEW</div>
<div style={{position:'absolute',top:190,width:'100%',textAlign:'center',opacity:fade(f,5)}}>
{data.cover&&<Img src={data.cover} style={{width: isTop?310:390,height:isTop?310:390,objectFit:'cover',boxShadow:'0 25px 70px #0008',borderRadius:8,transform:`scale(${.94+.06*fade(f,5,24)})`}}/>}
<div style={{fontSize:data.artist.length>60?36:46,fontWeight:700,marginTop:32,opacity:fade(f,24),padding:'0 70px',overflowWrap:'anywhere'}}>{data.artist||'ARTISTE'}</div>
<div style={{fontSize:data.album.length>80?28:32,color:'#d2cbd8',marginTop:14,padding:'0 70px',opacity:fade(f,38),overflowWrap:'anywhere'}}>{data.album||'Nom de l’album'}</div>
</div>
{isTracks&&<><div style={{position:'absolute',top:850,left:80,width:670}}><div style={{fontSize:24,letterSpacing:6,color:'#a9a0b6',marginBottom:35}}>TRACKLIST <span style={{letterSpacing:0}}> {page+1}/{t.pages.length}</span></div>{visible.map((track,i)=>{const a=fade(f,start+i*t.step,12);return <div key={track.id} style={{minHeight:track.rowHeight,display:'flex',alignItems:'center',gap:18,opacity:a,transform:`translateX(${(1-a)*22}px)`}}><span style={{width:17,height:17,borderRadius:'50%',background:category(track.score).color,flexShrink:0}}/><span style={{fontSize:34,lineHeight:'39px',flex:1,overflowWrap:'anywhere'}}>{track.title}</span><span style={{fontSize:28,color:category(track.score).color,marginLeft:10}}>{format(track.score)}</span></div>})}</div><div style={{position:'absolute',right:55,top:935,width:220}}>{categories.map(c=><div key={c.label} style={{fontSize:24,color:c.color,marginBottom:35}}>{c.label}</div>)}</div></>}
{isResult&&<div style={{position:'absolute',top:1000,width:'100%',textAlign:'center',opacity:fade(f,t.tracksEnd)}}><div style={{fontSize:25,letterSpacing:7,color:'#aaa0b6'}}>NOTE GLOBALE</div><div style={{fontSize:185,fontWeight:700,color:category(data.score).color,marginTop:35}}>{format(data.score)}<span style={{fontSize:55}}>/10</span></div></div>}
{isTop&&<div style={{position:'absolute',top:820,width:'100%',textAlign:'center'}}><div style={{fontSize:26,letterSpacing:8,color:'#b8adca',opacity:fade(f,t.resultEnd)}}>TOP 3</div>{data.top.map((id,i)=>{const track=data.tracks.find(x=>x.id===id);const a=fade(f,t.resultEnd+15+i*30,18);return <div key={i} style={{margin:'40px 65px',opacity:a,transform:`scale(${i===0?.90+.10*a:.97+.03*a})`,color:i===0?'#e1d0ff':'#e6e1ec',fontSize:track?.title.length>70?(i===0?32:28):(i===0?53:39),fontWeight:i===0?700:400,overflowWrap:'anywhere'}}><div style={{fontSize:20,color:'#9c8cae',marginBottom:12}}>0{i+1}</div>{track?.title||'—'}</div>})}<div style={{marginTop:55,fontSize:62,fontWeight:700,color:category(data.score).color,opacity:fade(f,t.topEnd)}}>{format(data.score)}<span style={{fontSize:30}}>/10</span></div></div>}
<div style={{position:'absolute',bottom:90,width:'100%',textAlign:'center',fontSize:20,letterSpacing:5,color:'#9a8da8'}}>ÉCOUTER. RESSENTIR. NOTER.</div>
</AbsoluteFill>}
